<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <NoWarn>$(NoWarn);AVLN3001</NoWarn>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Irihi.Ursa" Version="2.1.0" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="2.1.0" />
        <PackageReference Include="Packaging.Targets">
            <Version>0.1.232-*</Version>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Semi.Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Semi.Avalonia.DataGrid" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="$(AvaloniaVersion)" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="CommandLineParser" Version="2.9.1" />
        <PackageReference Include="System.Reactive" Version="6.0.1" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="Prism.Core" Version="9.0.537" />
        <PackageReference Include="Prism.Avalonia" Version="9.0.537.11130" />
        <PackageReference Include="Prism.DryIoc.Avalonia" Version="9.0.537.11130" />
    </ItemGroup>
</Project>
